version: '3.8'

services:
  line-gemini-hatena:
    build: .
    container_name: line-gemini-hatena-app
    ports:
      - "8000:8000"
    environment:
      # 環境変数は .env ファイルまたは外部で設定
      - FLASK_ENV=production
      - LOG_LEVEL=INFO
    env_file:
      - .env.production
    volumes:
      # ログの永続化
      - ./logs:/app/logs
      # アップロードファイルの永続化
      - ./uploads:/app/uploads
      # データベースの永続化（SQLiteの場合）
      - ./instance:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx リバースプロキシ（オプション）
  nginx:
    image: nginx:alpine
    container_name: line-gemini-hatena-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL証明書（必要な場合）
    depends_on:
      - line-gemini-hatena
    restart: unless-stopped

networks:
  default:
    name: line-gemini-hatena-network